class Reference():
    def __init__(self):
        self.all_dict_headers = [
            # basic information
            'INSTNM', 'CITY', 'STABBR', 'INSTURL', 'LOCALE', 'LATITUDE',
            'LONGITUDE', 'CCBASIC', 'CCSIZSET', 'RELAFFIL', 'REGION',

            # test-related
            'ADM_RATE', 'SATVR25', 'SATVRMID', 'SATVR75', 'SATMT25', 'SATMTMID',
            'SATMT75', 'SATWR25', 'SATWRMID','SATWR75', 'SAT_AVG', 'ACTCM25',
            'ACTCMMID', 'ACTCM75', 'ACTEN25', 'ACTENMID', 'ACTEN75', 'ACTMT25',
            'ACTMTMID', 'ACTMT75', 'ACTWR25', 'ACTWRMID', 'ACTWR75',
            
            # program distribution
            'PCIP01', 'PCIP03', 'PCIP04', 'PCIP05', 'PCIP09', 'PCIP10', 'PCIP11',
            'PCIP12', 'PCIP13', 'PCIP14', 'PCIP15', 'PCIP16', 'PCIP19', 'PCIP22',
            'PCIP23', 'PCIP24', 'PCIP25', 'PCIP26', 'PCIP27', 'PCIP29', 'PCIP30',
            'PCIP31', 'PCIP38', 'PCIP39', 'PCIP40', 'PCIP41', 'PCIP42',
            'PCIP43', 'PCIP44', 'PCIP45', 'PCIP46', 'PCIP47', 'PCIP48', 'PCIP49',
            'PCIP50', 'PCIP51', 'PCIP52', 'PCIP54',

            # undergrad distribution
            'UGDS', 'UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN',
            'UGDS_AIAN', 'UGDS_NHPI', 'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN',
            'UGDS_MEN', 'UGDS_WOMEN',

            # pricing
            'NPT4_PUB', 'NPT4_PRIV', 'NPT41_PUB', 'NPT42_PUB', 'NPT43_PUB',
            'NPT44_PUB', 'NPT45_PUB', 'NPT41_PRIV', 'NPT42_PRIV', 'NPT43_PRIV',
            'NPT44_PRIV', 'NPT45_PRIV', 'NPT4_048_PUB', 'NPT4_048_PRIV',
            'NPT4_3075_PUB', 'NPT4_3075_PRIV', 'NPT4_75UP_PUB', 'NPT4_75UP_PRIV',
            'COSTT4_A', 'COSTT4_P', 'TUITIONFEE_IN', 'TUITIONFEE_OUT', 'PCTFLOAN',
            'BOOKSUPPLY', 'ROOMBOARD_ON', 'OTHEREXPENSE_ON', 'ROOMBOARD_OFF',
            'OTHEREXPENSE_OFF', 'OTHEREXPENSE_FAM'
        ]
        self.locale_filter = {
            '11': 'City: Large (250,000+)',
            '12': 'City: Midsize (100,000-250,000)',
            '13': 'City: Small (<100,000)',
            '21': 'Suburb: Large (outside principal city, in urbanized area with 250,000+)',
            '22': 'Suburb: Midsize (outside principal city, in urbanized area with 100,000-250,000)',
            '23': 'Suburb: Small (outside principal city, in urbanized area with <100,000)',
            '31': 'Town: Fringe (in urban cluster <10 mi from an urbanized area)',
            '32': 'Town: Distant (in urban cluster 10-35 mi from an urbanized area)',
            '33': 'Town: Remote (in urban cluster 35+ mi from an urbanized area)',
            '41': 'Rural: Fringe (rural territory <5 mi from an urbanized area or <2.5 mi from an urban cluster)',
            '42': 'Rural: Distant (rural territory 5-25 mi from an urbanized area or 2.5-10 mi from an urban cluster)',
            '43': 'Rural: Remote (rural territory 25+ mi from an urbanized area and 10+ mi from an urban cluster)'
        }
        self.carnegie_classification_basic_filter = {
            'n/a': 'n/a',
            '1': "Associate's Colleges: High Transfer-High Traditional",
            '2': "Associate's Colleges: High Transfer-Mixed Traditional/Nontraditional",
            '3': "Associate's Colleges: High Transfer-High Nontraditional",
            '4': "Associate's Colleges: Mixed Transfer/Career & Technical-High Traditional",
            '5': "Associate's Colleges: Mixed Transfer/Career & Technical-Mixed Traditional/Nontraditional",
            '6': "Associate's Colleges: Mixed Transfer/Career & Technical-High Nontraditional",
            '7': "Associate's Colleges: High Career & Technical-High Traditional",
            '8': "Associate's Colleges: High Career & Technical-Mixed Traditional/Nontraditional",
            '9': "Associate's Colleges: High Career & Technical-High Nontraditional",
            '10': "Special Focus Two-Year: Health Professions",
            '11': "Special Focus Two-Year: Technical Professions",
            '12': "Special Focus Two-Year: Arts & Design",
            '13': "Special Focus Two-Year: Other Fields",
            '14': "Baccalaureate/Associate's Colleges: Associate's Dominant",
            '15': "Doctoral Universities: Very High Research Activity",
            '16': "Doctoral Universities: High Research Activity",
            '17': "Doctoral/Professional Universities",
            '18': "Master's Colleges & Universities: Larger Programs",
            '19': "Master's Colleges & Universities: Medium Programs",
            '20': "Master's Colleges & Universities: Small Programs",
            '21': "Baccalaureate Colleges: Arts & Sciences Focus",
            '22': "Baccalaureate Colleges: Diverse Fields",
            '23': "Baccalaureate/Associate's Colleges: Mixed Baccalaureate/Associate's",
            '24': "Special Focus Four-Year: Faith-Related Institutions",
            '25': "Special Focus Four-Year: Medical Schools & Centers",
            '26': "Special Focus Four-Year: Other Health Professions Schools",
            '27': "Special Focus Four-Year: Engineering Schools",
            '28': "Special Focus Four-Year: Other Technology-Related Schools",
            '29': "Special Focus Four-Year: Business & Management Schools",
            '30': "Special Focus Four-Year: Arts, Music & Design Schools",
            '31': "Special Focus Four-Year: Law Schools",
            '32': "Special Focus Four-Year: Other Special Focus Institutions",
            '33': "Tribal Colleges"
        }
        self.carnegie_classification_size_filter = {
            'n/a': 'n/a',
            '1': 'Two-year, very small',
            '2': 'Two-year, small',
            '3': 'Two-year, medium',
            '4': 'Two-year, large',
            '5': 'Two-year, very large',
            '6': 'Four-year, very small, primarily nonresidential',
            '7': 'Four-year, very small, primarily residential',
            '8': 'Four-year, very small, highly residential',
            '9': 'Four-year, small, primarily nonresidential',
            '10': 'Four-year, small, primarily residential',
            '11': 'Four-year, small, highly residential',
            '12': 'Four-year, medium, primarily nonresidential',
            '13': 'Four-year, medium, primarily residential',
            '14': 'Four-year, medium, highly residential',
            '15': 'Four-year, large, primarily nonresidential',
            '16': 'Four-year, large, primarily residential',
            '17': 'Four-year, large, highly residential',
            '18': 'Exclusively graduate/professional'
        }
        self.religous_affiliation_filter = {
            'n/a': 'n/a',
            '22': 'American Evangelical Lutheran Church',
            '24': 'African Methodist Episcopal Zion Church',
            '27': 'Assemblies of God Church',
            '28': 'Brethren Church',
            '30': 'Roman Catholic',
            '33': 'Wisconsin Evangelical Lutheran Synod',
            '34': 'Christ and Missionary Alliance Church',
            '35': 'Christian Reformed Church',
            '36': 'Evangelical Congregational Church',
            '37': 'Evangelical Covenant Church of America',
            '38': 'Evangelical Free Church of America',
            '39': 'Evangelical Lutheran Church',
            '40': 'International United Pentecostal Church',
            '41': 'Free Will Baptist Church',
            '42': 'Interdenominational',
            '43': 'Mennonite Brethren Church',
            '44': 'Moravian Church',
            '45': 'North American Baptist',
            '47': 'Pentecostal Holiness Church',
            '48': 'Christian Churches and Churches of Christ',
            '49': 'Reformed Church in America',
            '50': 'Episcopal Church, Reformed',
            '51': 'African Methodist Episcopal',
            '52': 'American Baptist',
            '53': 'American Lutheran',
            '54': 'Baptist',
            '55': 'Christian Methodist Episcopal',
            '57': 'Church of God',
            '58': 'Church of Brethren',
            '59': 'Church of the Nazarene',
            '60': 'Cumberland Presbyterian',
            '61': 'Christian Church (Disciples of Christ)',
            '64': 'Free Methodist',
            '65': 'Friends',
            '66': 'Presbyterian Church (USA)',
            '67': 'Lutheran Church in America',
            '68': 'Lutheran Church - Missouri Synod',
            '69': 'Mennonite Church',
            '71': 'United Methodist',
            '73': 'Protestant Episcopal',
            '74': 'Churches of Christ',
            '75': 'Southern Baptist',
            '76': 'United Church of Christ',
            '77': 'Protestant, not specified',
            '78': 'Multiple Protestant Denomination',
            '79': 'Other Protestant',
            '80': 'Jewish',
            '81': 'Reformed Presbyterian Church',
            '84': 'United Brethren Church',
            '87': '	Missionary Church Inc',
            '88': 'Undenominational',
            '89': 'Wesleyan',
            '91': 'Greek Orthodox',
            '92': 'Russian Orthodox',
            '93': 'Unitarian Universalist',
            '94': 'Latter Day Saints (Mormon Church)',
            '95': 'Seventh Day Adventists',
            '97': 'The Presbyterian Church in America',
            '99': 'Other (none of the above)',
            '100': 'Original Free Will Baptist',
            '101': 'Ecumenical Christian',
            '102': 'Evangelical Christian',
            '103': 'Presbyterian',
            '105': 'General Baptist',
            '106': 'Muslim',
            '107': 'Plymouth Brethren',
            '108': 'Evangelical Protestant'
        }
        self.geographic_region_filter = {
            '0': 'U.S. Service Schools',
            '1': 'New England',
            '2': 'Mid East',
            '3': 'Great Lakes',
            '4': 'Plains',
            '5': 'Southeast',
            '6': 'Southwest',
            '7': 'Rocky Mountains',
            '8': 'Far West',
            '9': 'Outlying Areas'
        }
        self.value_filters = {
            'LOCALE': self.locale_filter,
            'CCBASIC': self.carnegie_classification_basic_filter,
            'CCSIZSET': self.carnegie_classification_size_filter,
            'RELAFFIL': self.religous_affiliation_filter,
            'REGION': self.geographic_region_filter
        }
        self.key_filters = {
            'INSTNM': 'Institution Name',
            'STABBR': 'State',
            'CITY': 'City',
            'INSTURL': 'Homepage Link',
            'LOCALE': 'Local Population Size',
            'LATITUDE': 'LATITUDE',
            'LONGITUDE': 'LONGITUDE',
            'CCBASIC': 'Carnegie Classification - Basic',
            'CCSIZSET': 'Carnegie Classification - Size',
            'RELAFFIL': 'Religious Affiliation',
            'REGION': 'Geographic Region',
            
            'ADM_RATE': 'Admissions Rate',
            'SATVR25': 'SAT Reading 25%',
            'SATVRMID': 'SAT Reading 50%',
            'SATVR75': 'SAT Reading 75%',
            'SATMT25': 'SAT Math 25%',
            'SATMTMID': 'SAT Math 50%',
            'SATMT75': 'SAT Math 75%',
            'SATWR25': 'SAT Writing 25%',
            'SATWRMID': 'SAT Writing 50%',
            'SATWR75': 'SAT Writing 75%',
            'SAT_AVG': 'SAT Average',
            'ACTCM25': 'ACT Cumulative 25%',
            'ACTCMMID': 'ACT Cumulative 50%',
            'ACTCM75': 'ACT Cumulative 75%',
            'ACTEN25': 'ACT English 25%',
            'ACTENMID': 'ACT English 50%',
            'ACTEN75': 'ACT English 75%',
            'ACTMT25': 'ACT Math 25%',
            'ACTMTMID': 'ACT Math 50%',
            'ACTMT75': 'ACT Math 75%',
            'ACTWR25': 'ACT Writing 25%',
            'ACTWRMID': 'ACT Writing 50%',
            'ACTWR75': 'ACT Writing 75%',

            'PCIP01': 'Agriculture, Agriculture Operations, and Related Sciences',
            'PCIP03': 'Natural Resources and Conservation',
            'PCIP04': 'Architecture and Related Services',
            'PCIP05': 'Area, Ethnic, Cultural, Gender, and Group Studies',
            'PCIP09': 'Communication, Journalism, and Related Programs',
            'PCIP10': 'Communications Technologies/Technicians and Support Services',
            'PCIP11': 'Computer and Information Sciences and Support Services',
            'PCIP12': 'Personal and Culinary Services',
            'PCIP13': 'Education',
            'PCIP14': 'Engineering',
            'PCIP15': 'Engineering Technologies and Engineering-Related Fields',
            'PCIP16': 'Foreign Languages, Literatures, and Linguistics',
            'PCIP19': 'Family and Consumer Sciences/Human Sciences',
            'PCIP22': 'Legal Professions and Studies',
            'PCIP23': 'English Language and Literature/Letters',
            'PCIP24': 'Liberal Arts and Sciences, General Studies and Humanities',
            'PCIP25': 'Library Science',
            'PCIP26': 'Biological and Biomedical Sciences',
            'PCIP27': 'Mathematics and Statistics',
            'PCIP29': 'Military Technologies and Applied Sciences',
            'PCIP30': 'Multi/Interdisciplinary Studies',
            'PCIP31': 'Parks, Recreation, Leisure, and Fitness Studies',
            'PCIP38': 'Philosophy and Religious Studies',
            'PCIP39': 'Theology and Religious Vocations',
            'PCIP40': 'Physical Sciences',
            'PCIP41': 'Science Technologies/Technicians',
            'PCIP42': 'Psychology',
            'PCIP43': 'Homeland Security, Law Enforcement, Firefighting and Related Protective Services',
            'PCIP44': 'Public Administration and Social Service Professions',
            'PCIP45': 'Social Sciences',
            'PCIP46': 'Construction Trades',
            'PCIP47': 'Mechanic and Repair Technologies/Technicians',
            'PCIP48': 'Precision Production',
            'PCIP49': 'Transportation and Materials Moving',
            'PCIP50': 'Visual and Performing Arts',
            'PCIP51': 'Health Professions and Related Programs',
            'PCIP52': 'Business, Management, Marketing, and Related Support Services',
            'PCIP54': 'History',

            # undergrad distribution
            'UGDS': 'Undergrad Size',
            'UGDS_WHITE': 'Undergrad % White',
            'UGDS_BLACK': 'Undergrad % Black',
            'UGDS_HISP': 'Undergrad % Hispanic',
            'UGDS_ASIAN': 'Undergrad % Asian',
            'UGDS_AIAN': 'Undergrad % American Indian / Alaska Native',
            'UGDS_NHPI': 'Undergrad % Native Hawaiian / Pacific Islander',
            'UGDS_2MOR': 'Undergrad % 2+ races',
            'UGDS_NRA': 'Undergrad % Non-resident aliens',
            'UGDS_UNKN': 'Undergrad % Unknown',
            'UGDS_MEN': 'Undegrad % Male',
            'UGDS_WOMEN': 'Undegrad % Women',

            # pricing
            'NPT4_PUB': 'Avg Net $',
            'NPT4_PRIV': 'Avg Net $',
            'NPT41_PUB': 'Avg Net $ for $0-$30,000 family income',
            'NPT42_PUB': 'Avg Net $ for $30,001-$48,000 family income',
            'NPT43_PUB': 'Avg Net $ for $48,001-$75,000 family income',
            'NPT44_PUB': 'Avg Net $ for $75,001-$110,000 family income',
            'NPT45_PUB': 'Avg Net $ for $110,000+ family income',
            'NPT41_PRIV': 'Avg Net $ for $0-$30,000 family income',
            'NPT42_PRIV': 'Avg Net $ for $30,001-$48,000 family income',
            'NPT43_PRIV': 'Avg Net $ for $48,001-$75,000 family income',
            'NPT44_PRIV': 'Avg Net $ for $48,001-$75,000 family income',
            'NPT45_PRIV': 'Avg Net $ for $110,000+ family income',
            'NPT4_048_PUB': 'Avg Net $ for $0-$48,000 family income',
            'NPT4_048_PRIV': 'Avg Net $ for $0-$48,000 family income',
            'NPT4_3075_PUB': 'Avg Net $ for $30,001-$75,000 family income',
            'NPT4_3075_PRIV': 'Avg Net $ for $30,001-$75,000 family income',
            'NPT4_75UP_PUB': 'Avg Net $ for $75,000+ family income',
            'NPT4_75UP_PRIV': 'Avg Net $ for $75,000+ family income',
            'COSTT4_A': 'Avg $ of attendance',
            'COSTT4_P': 'Avg $ of attendance',
            'TUITIONFEE_IN': 'In-state tuition and fees',
            'TUITIONFEE_OUT': 'Out-of-state tuition and fees',
            'PCTFLOAN': 'Undegrad % that got federal loan',
            'BOOKSUPPLY': '$ of attendance: estimated books and supplies',
            'ROOMBOARD_ON': '$ of attendance: on-campus room and board',
            'OTHEREXPENSE_ON': '$ of attendance: on-campus other expenses',
            'ROOMBOARD_OFF': '$ of attendance: off-campus room and board',
            'OTHEREXPENSE_OFF': '$ of attendance: off-campus other expenses',
            'OTHEREXPENSE_FAM': '$ of attendance: with-family other expenses'
        }

        state_abbreviations = [
            "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME",
            "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA",
            "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"
        ]
        self.states_count_dict = dict.fromkeys(state_abbreviations, 0)