_ = {
'NPT4_PUB': 'Avg Net $',
'NPT4_PRIV': 'Avg Net $',
'NPT41_PUB': 'Avg Net $ for $0-$30,000 family income (public institutions)',
'NPT42_PUB': 'Avg Net $ for $30,001-$48,000 family income (public institutions)',
'NPT43_PUB': 'Avg Net $ for $48,001-$75,000 family income (public institutions)',
'NPT44_PUB': 'Avg Net $ for $75,001-$110,000 family income (public institutions)',
'NPT45_PUB': 'Avg Net $ for $110,000+ family income (public institutions)',
'NPT41_PRIV': 'Avg Net $ for $0-$30,000 family income (private for-profit and nonprofit institutions)',
'NPT42_PRIV': 'Avg Net $ for $30,001-$48,000 family income (private for-profit and nonprofit institutions)',
'NPT43_PRIV': 'Avg Net $ for $48,001-$75,000 family income (private for-profit and nonprofit institutions)',
'NPT44_PRIV': 'Avg Net $ for $48,001-$75,000 family income (private for-profit and nonprofit institutions)',
'NPT45_PRIV': 'Avg Net $ for $110,000+ family income (private for-profit and nonprofit institutions)',
'NPT4_048_PUB': 'Avg Net $ for $0-$48,000 family income (public institutions)',
'NPT4_048_PRIV': 'Avg Net $ for $0-$48,000 family income (private for-profit and nonprofit institutions)',
'NPT4_3075_PUB': 'Avg Net $ for $30,001-$75,000 family income (public institutions)',
'NPT4_3075_PRIV': 'Avg Net $ for $30,001-$75,000 family income (private for-profit and nonprofit institutions)',
'NPT4_75UP_PUB': 'Avg Net $ for $75,000+ family income (public institutions)',
'NPT4_75UP_PRIV': 'Avg Net $ for $75,000+ family income (private for-profit and nonprofit institutions)',
'COSTT4_A': 'Avg $ of attendance (academic year institutions)',
'COSTT4_P': 'Avg $ of attendance (program-year institutions)',
'TUITIONFEE_IN': 'In-state tuition and fees',
'TUITIONFEE_OUT': 'Out-of-state tuition and fees',
'PCTFLOAN': 'Undegrad % that got federal loan',
'BOOKSUPPLY': '$ of attendance: estimated books and supplies',
'ROOMBOARD_ON': '$ of attendance: on-campus room and board',
'OTHEREXPENSE_ON': '$ of attendance: on-campus other expenses',
'ROOMBOARD_OFF': '$ of attendance: off-campus room and board',
'OTHEREXPENSE_OFF': '$ of attendance: off-campus other expenses',
'OTHEREXPENSE_FAM': '$ of attendance: with-family other expenses'}

l = []
keys = [
    'Avg Net $',
    'Avg Net $ for $0-$48,000 family income',
    'Avg Net $ for $0-$30,000 family income',
    'Avg Net $ for $30,001-$48,000 family income',
    'Avg Net $ for $30,001-$75,000 family income',
    'Avg Net $ for $48,001-$75,000 family income',
    'Avg Net $ for $75,001-$110,000 family income',
    'Avg Net $ for $75,000+ family income',
    'Avg Net $ for $110,000+ family income',
    'Avg $ of attendance (academic year institutions)', 'Avg $ of attendance (program-year institutions)',
    'In-state tuition and fees', 'Out-of-state tuition and fees', 'Undegrad % that got federal loan',
    '$ of attendance: estimated books and supplies', '$ of attendance: on-campus room and board',
    '$ of attendance: on-campus other expenses', '$ of attendance: off-campus room and board',
    '$ of attendance: off-campus other expenses', '$ of attendance: with-family other expenses'
    ]
for key in keys:
    print(f'<p id="{key}">{key}</p>')